### ISSUE TITLE
RSocketResumableTransport not working

### ISSUE THREAD

**Issue by shankarwww** [rsocket/rsocket-js#101]
RSocketResumableTransport does not seems to be working. I have below code where i am using RSocketResumableTransport but it never connects to the server(spring-boot version 2.4.0-M1). I am using rsocket-websocket-client": "0.0.19" version.

```js
import { Injectable } from '@angular/core';
import { IdentitySerializer, JsonSerializer, RSocket, RSocketClient, RSocketResumableTransport } from 'rsocket-core';
import RSocketWebSocketClient from 'rsocket-websocket-client';

@Injectable({ providedIn: 'root' })
export class RSocketResumableConnector {
    private client: RSocketClient;
    private rsocket: RSocket;

    constructor() {
        console.log('RSocketResumableConnector loaded...');
        this.createConnection();
    }

    public createConnection() {
        const resumeToken = Buffer.from('tweet.all');
        const bufferSize = 128;
        const sessionDurationSeconds = 20;

        const resumableTransport = new RSocketResumableTransport(
            () =>
                new RSocketWebSocketClient({
                    url: 'ws://localhost:7000/tweetsocket',
                }),
            {
                bufferSize, // max number of sent & pending frames to buffer before failing
                resumeToken, // unique identifier the session across connections
                sessionDurationSeconds,
            }
        );

        // Create an instance of a client
        this.client = new RSocketClient({
            // send/receive objects instead of strings/buffers
            serializers: {
                data: JsonSerializer,
                metadata: IdentitySerializer,
            },
            setup: {
                payload: {
                    data: 'angular-client',
                    metadata: String.fromCharCode('shell-client'.length) + 'shell-client',
                },
                dataMimeType: 'application/json',
                metadataMimeType: 'message/x.rsocket.routing.v0',
                keepAlive: 5000,
                lifetime: 60000,
            },
            transport: resumableTransport,
        });

        // staart resumableTransport
        let start = true;
        resumableTransport.connectionStatus().subscribe({
            onNext: (status) => {
                console.log('Resumable transport status changed: ' + status.kind);

                if (status.kind === 'NOT_CONNECTED') {
                    if (!start) {
                        console.log('Resumable transport disconnected, retrying...');
                        setTimeout(() => resumableTransport.connect());
                    } else {
                        start = false;
                    }
                }
            },
            onSubscribe: (resumeSubscription) => {
                resumeSubscription.request(Number.MAX_SAFE_INTEGER);
            },
        });

        setTimeout(() => {}, 30000000);

        // now create a socket
        this.client.connect().subscribe({
            onComplete: (socket: RSocket) => {
                console.log('socket in created', socket);
                this.rsocket = socket;
            },
            onError: (error) => console.error('Connection has been refused due to', error),
            onSubscribe: (cancel) => {
                console.log('client subscription done..');
            },
            onNext: (data) => {
                console.log('data is', data);
            },
        });
    }

    public disconnectClient() {
        if (this.client !== undefined) {
            this.client.close();
        }
    }

    public getRSocket(): RSocket {
        return this.rsocket;
    }
}
```
The continuous error in the browser console is below. This errror keeps on repeating till timeout:
Resumable transport disconnected, retrying...
Resumable transport status changed: CONNECTING
Resumable transport status changed: NOT_CONNECTED
Resumable transport disconnected, retrying...

Please let me know if i m doing something wrong ?

**Comment by OlegDokuka** [comment]
Hi @shankarwww!

Thanks for asking that!
Unfortunately, resumability was broken in 1.1.0-M1 which (as far as I know) is the dependency in M1 release of the spring-boot project. However, that should   be fixed with the latest 1.1.0-M2 release that we did yesterday. 1.1.0-M2 of RSocket-Java should be a dependency in 2.4.0-M2 of spring boot.

Thus give it a try and let me know if it worked for you. 

Also, 2.3.x should also work properly with resumability since it depende on 1.0.x where resumability have not been touched yet

**Comment by shankarwww** [comment]
i have changed the version to **2.3.3.RELEASE** but issue remains the same for me. Error on the java-script client remains the same :
Resumable transport disconnected, retrying...
Resumable transport status changed: CONNECTING
Resumable transport status changed: NOT_CONNECTED
Resumable transport disconnected, retrying...


Error on spring boot side is:

java.lang.Exception: ChannelOperation dispose stack
	at reactor.netty.channel.ChannelOperations.dispose(ChannelOperations.java:161) [reactor-netty-0.9.11.RELEASE.jar:0.9.11.RELEASE]
	at reactor.netty.tcp.TcpServerBind$ChildObserver.onStateChange(TcpServerBind.java:263) [reactor-netty-0.9.11.RELEASE.jar:0.9.11.RELEASE]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:432) [reactor-netty-0.9.11.RELEASE.jar:0.9.11.RELEASE]
	at reactor.netty.http.server.WebsocketServerOperations.lambda$onInboundNext$1(WebsocketServerOperations.java:151) [reactor-netty-0.9.11.RELEASE.jar:0.9.11.RELEASE]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at reactor.netty.http.server.WebsocketServerOperations.sendCloseNow(WebsocketServerOperations.java:244) [reactor-netty-0.9.11.RELEASE.jar:0.9.11.RELEASE]
	at reactor.netty.http.server.WebsocketServerOperations.onInboundNext(WebsocketServerOperations.java:149) [reactor-netty-0.9.11.RELEASE.jar:0.9.11.RELEASE]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96) ~[reactor-netty-0.9.11.RELEASE.jar:0.9.11.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.rsocket.transport.netty.server.BaseWebsocketServerTransport$PongHandler.channelRead(BaseWebsocketServerTransport.java:63) ~[rsocket-transport-netty-1.0.2.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]

**Comment by OlegDokuka** [comment]
@shankarwww can you show please how do you do your server setup?

**Comment by shankarwww** [comment]
### below is my application.yml file
```
server:
  port: 8081
  shutdown: graceful
  
spring:
  lifecycle:
    timeout-per-shutdown-phase: 40s
  main:
    lazy-initialization: false
    
  r2dbc:
    url: r2dbc:postgres://localhost:5432/postgres
    username: ****
    password: *****

  output:
    ansi:
      enabled: always
      
  rsocket:
    server:
      port: 7000
      mapping-path: /tweetsocket
      transport: websocket
      
  cloud:
    stream:
      function.definition: tweetFluxReceiver;
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
      bindings:
        tweetReceiver-in-0:
          destination: all-tweets
        tweetFluxReceiver-in-0:
          destination: all-tweets
       
logging:
  level:
    root: trace
    #org.springframework: info
    #org.springframework.data.r2dbc: info
    #org.springframework.data.jdbc.core: info
    #org.springframework.data.jdbc.core.StatementCreatorUtils: info
    #org.hibernate.sql: info
    #io.rsocket: info
```

### Below is my pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.0-M1</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.sg.projects</groupId>
	<artifactId>twitter-java</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>twitter-java</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-r2dbc</artifactId>
		</dependency>
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-rsocket</artifactId>
        </dependency>
        <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
		<dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-messaging</artifactId>
        </dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>io.r2dbc</groupId>
			<artifactId>r2dbc-postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
```

There is no other specific configuration. Then i just use code like below in any `@Controller` class
```
@MessageMapping("tweet.all")
    public Flux<TweetEntity> getAllTweets(@Payload UserBean userBean) {
        log.info("going to get all tweets: {}", userBean);
        return this.tweetService.getAllTweets();
    }
```

Please let me know if u need more information.

**Comment by OlegDokuka** [comment]
Both sides have to have resumability properly configured. You may find how to so in pure RSocket-Java from that following example - https://github.com/rsocket/rsocket-java/blob/master/rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java#L68. To do a similar configuration in spring you can do the same via -> https://github.com/spring-projects/spring-boot/blob/7d5f33170e1fddfa45af1555bc8040849159c929/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/rsocket/server/RSocketServerCustomizer.java#L28

**Comment by shankarwww** [comment]
i used below code but still not working. For client config, i have already posted the js code in the top.

```
@Component
public class RSocketServerCustomizerImpl implements RSocketServerCustomizer {

    @Override
    public void customize(RSocketServer rSocketServer) {

        rSocketServer
                .resume(resumeConfig());

    }

    private Resume resumeConfig() {
        return new Resume()
                .sessionDuration(Duration.ofMinutes(5))
                .retry(
                        Retry.fixedDelay(Long.MAX_VALUE, Duration.ofSeconds(1))
                                .doBeforeRetry(s -> log.debug("Disconnected. Trying to resume...")));
    }
}
```

Can you redirect me to a spring boot config(server config) for the same ?

**Comment by viglucci** [comment]
Closing this due to inactivity. If there are potentially existing issues with `rsocket-java` in regards to Resumability, it would be best to re-open on the `rsocket-java` project.

Additionally, for anyone coming across this issue in the future, a new example for Resumability exists: https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-examples/src/ResumeExample.js
